apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: polis-file-server
  name: polis-file-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: polis-file-server
  template:
    metadata:
      labels:
        app: polis-file-server
    spec:
      containers:
      - image: polisdemo/file-server:dev
        imagePullPolicy: Always
        name: polis-file-server
        ports:
        - containerPort: 8080
      initContainers:
      - image: polisdemo/client-participation:dev
        imagePullPolicy: Always
        name: polis-client-participation
      - image: polisdemo/client-admin:dev
        imagePullPolicy: Always
        name: polis-client-admin
      - image: polisdemo/client-report:dev
        imagePullPolicy: Always
        name: polis-client-report
      restartPolicy: Always
