apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: file-server
  name: file-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: file-server
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.network/polis-dev: "true"
        io.kompose.service: file-server
    spec:
      containers:
      - image: polisdemo/file-server:dev
        imagePullPolicy: ""
        name: polis-file-server
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
