{{- if .Values.host }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: polis 
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod" 

spec:
  tls:
  - hosts:
    - {{ .Values.host }}
    secretName: polis-tls
  rules:
  - host: {{ .Values.host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: polis-server
          servicePort: 5000
{{- end -}}
