apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: math
  name: math
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: math
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.network/polis-dev: "true"
        io.kompose.service: math
    spec:
      containers:
      - env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              key: DATABASE_URL
              name: math-docker-dev-env
        - name: WEBSERVER_PASS
          valueFrom:
            configMapKeyRef:
              key: WEBSERVER_PASS
              name: math-docker-dev-env
        - name: WEBSERVER_USERNAME
          valueFrom:
            configMapKeyRef:
              key: WEBSERVER_USERNAME
              name: math-docker-dev-env
        image: polisdemo/math:dev
        imagePullPolicy: ""
        name: polis-math
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
