apiVersion: v1
kind: Service
metadata:
  labels:
    app: polis
  name: polis-server
spec:
  ports:
  - name: polis-server
    port: 5000
    targetPort: 5000
  selector:
    app: polis
status:
  loadBalancer: {}
