apiVersion: v1
kind: Service
metadata:
  labels:
    app: polis-server
  name: server
spec:
  ports:
  - name: server
    port: 5000
    targetPort: 5000
  selector:
    app: polis-server
status:
  loadBalancer: {}
