apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: server
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: server
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.network/polis-dev: "true"
        io.kompose.service: server
    spec:
      containers:
      - env:
        - name: ADMIN_EMAILS
          valueFrom:
            configMapKeyRef:
              key: ADMIN_EMAILS
              name: server-docker-dev-env
        - name: ADMIN_EMAIL_DATA_EXPORT
          valueFrom:
            configMapKeyRef:
              key: ADMIN_EMAIL_DATA_EXPORT
              name: server-docker-dev-env
        - name: ADMIN_EMAIL_DATA_EXPORT_TEST
          valueFrom:
            configMapKeyRef:
              key: ADMIN_EMAIL_DATA_EXPORT_TEST
              name: server-docker-dev-env
        - name: ADMIN_EMAIL_EMAIL_TEST
          valueFrom:
            configMapKeyRef:
              key: ADMIN_EMAIL_EMAIL_TEST
              name: server-docker-dev-env
        - name: ADMIN_UIDS
          valueFrom:
            configMapKeyRef:
              key: ADMIN_UIDS
              name: server-docker-dev-env
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              key: AWS_REGION
              name: server-docker-dev-env
        - name: DATABASE_FOR_READS_NAME
          valueFrom:
            configMapKeyRef:
              key: DATABASE_FOR_READS_NAME
              name: server-docker-dev-env
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              key: DATABASE_URL
              name: server-docker-dev-env
        - name: DEV_MODE
          valueFrom:
            configMapKeyRef:
              key: DEV_MODE
              name: server-docker-dev-env
        - name: DISABLE_INTERCOM
          valueFrom:
            configMapKeyRef:
              key: DISABLE_INTERCOM
              name: server-docker-dev-env
        - name: DOMAIN_OVERRIDE
          valueFrom:
            configMapKeyRef:
              key: DOMAIN_OVERRIDE
              name: server-docker-dev-env
        - name: EMAIL_TRANSPORT_TYPES
          valueFrom:
            configMapKeyRef:
              key: EMAIL_TRANSPORT_TYPES
              name: server-docker-dev-env
        - name: MATH_ENV
          valueFrom:
            configMapKeyRef:
              key: MATH_ENV
              name: server-docker-dev-env
        - name: POLIS_FROM_ADDRESS
          valueFrom:
            configMapKeyRef:
              key: POLIS_FROM_ADDRESS
              name: server-docker-dev-env
        - name: PORT
          valueFrom:
            configMapKeyRef:
              key: PORT
              name: server-docker-dev-env
        - name: SHOULD_USE_TRANSLATION_API
          valueFrom:
            configMapKeyRef:
              key: SHOULD_USE_TRANSLATION_API
              name: server-docker-dev-env
        - name: STATIC_FILES_ADMINDASH_PORT
          valueFrom:
            configMapKeyRef:
              key: STATIC_FILES_ADMINDASH_PORT
              name: server-docker-dev-env
        - name: STATIC_FILES_HOST
          valueFrom:
            configMapKeyRef:
              key: STATIC_FILES_HOST
              name: server-docker-dev-env
        - name: STATIC_FILES_PORT
          valueFrom:
            configMapKeyRef:
              key: STATIC_FILES_PORT
              name: server-docker-dev-env
        - name: STRIPE_SECRET_KEY
          valueFrom:
            configMapKeyRef:
              key: STRIPE_SECRET_KEY
              name: server-docker-dev-env
        - name: WEBSERVER_PASS
          valueFrom:
            configMapKeyRef:
              key: WEBSERVER_PASS
              name: server-docker-dev-env
        - name: WEBSERVER_USERNAME
          valueFrom:
            configMapKeyRef:
              key: WEBSERVER_USERNAME
              name: server-docker-dev-env
        image: polisdemo/server:dev
        imagePullPolicy: ""
        name: polis-server
        ports:
        - containerPort: 5000
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
