kind: "PersistentVolumeClaim"
apiVersion: "v1"
metadata:
  name: {{ .Release.Name }}-data-pvc
  labels:
    app: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: {{ .Values.volumeSize }}
---
kind: "PersistentVolumeClaim"
apiVersion: "v1"
metadata:
  name: {{ .Release.Name }}-db-pvc
  labels:
    app: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 1Gi
