apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb-ip
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: {{ .Values.image.port }}
    protocol: TCP
  selector:
    app: {{ .Release.Name }}
