apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  serviceName: {{ .Release.Name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.image.tag }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.image.port }}
        env:
          - name: SOLID_CONFIG_FILE
            value: "/opt/cm/config.json"
          - name: DEBUG
            value: "solid:*"
        {{- with .Values.image.env}}
          {{- toYaml . | nindent 10 }}
        {{- end }}
        volumeMounts:
          - name: {{ .Release.Name }}-tls
            mountPath: "/opt/ssl"
            readOnly: true
          - name: {{ .Release.Name }}-data
            mountPath: "/var/lib/solid/data"
          - name: {{ .Release.Name }}-db
            mountPath: "/var/lib/solid/db"
          - name: {{ .Release.Name }}-config
            mountPath: "/opt/cm"
      volumes:
        - name: {{ .Release.Name }}-tls
          secret:
            secretName: {{ .Release.Name }}-tls
        - name: {{ .Release.Name }}-config
          configMap:
            name: {{ .Release.Name }}-cm
            items:
            - key: json
              path: config.json
      imagePullSecrets:
      - name: {{ .Release.Name }}-image-pull-secret
  volumeClaimTemplates:
  - metadata:
      name: {{ .Release.Name }}-data
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: gp2
      resources:
        requests:
          storage: {{ .Values.dataSize }}
  - metadata:
      name: {{ .Release.Name }}-db
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: gp2
      resources:
        requests:
          storage: {{ .Values.dbSize }}
