{{- if .Values.host }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: {{ .Values.issuer }}
    nginx.ingress.kubernetes.io/proxy-body-size: 8m
spec:
  tls:
  - hosts:
    - {{ .Values.host | quote }}
    - {{ printf "*.%s" .Values.host | quote }}
    secretName: {{ .Release.Name }}-tls
  rules:
  - host: {{ .Values.host | quote }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Release.Name }}
          servicePort: 80
  - host: {{ printf "*.%s" .Values.host | quote }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Release.Name }}
          servicePort: 80
{{- end -}}
